# Generated by Django 5.1.4 on 2025-01-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relay_id', models.IntegerField(unique=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
